### PR TITLE
Fix Changelog dates to YYYY-MM-DD format

### PR DESCRIPTION
**Pull request by anthowen**
Hope this would be a good start-off with zksync!

### CODE REVIEW

**Comment by StanislavBreadless** [comment]
Hi @anthowen 

Thank you for help :) I have walked through all the other changelog files and realized that we don't have a consistent way to represent the dates. For instance [here](https://github.com/matter-labs/zksync/blob/master/changelog/core.md#release-2021-02-19) we use the YYYY-MM-DD format, while [here](https://github.com/matter-labs/zksync/blob/master/changelog/contracts.md#2021-31-05) we don't.

Could you please go through all the changelog files and change the format to YYYY-MM-DD?

**Comment by anthowen** [comment]
> Hi @anthowen
> 
> Thank you for help :) I have walked through all the other changelog files and realized that we don't have a consistent way to represent the dates. For instance [here](https://github.com/matter-labs/zksync/blob/master/changelog/core.md#release-2021-02-19) we use the YYYY-MM-DD format, while [here](https://github.com/matter-labs/zksync/blob/master/changelog/contracts.md#2021-31-05) we don't.
> 
> Could you please go through all the changelog files and change the format to YYYY-MM-DD?

Ok sure. No problem

**Comment by anthowen** [comment]
@StanislavBreadless I updated the PR.

**Comment by StanislavBreadless** [comment]
> @StanislavBreadless I updated the PR.

Could you please update the `js-sdk.md` and the `rust-sdk.md` as well?

**Comment by anthowen** [comment]
> > @StanislavBreadless I updated the PR.
> 
> Could you please update the `js-sdk.md` and the `rust-sdk.md` as well?

Ok sure.

**Comment by anthowen** [comment]
@StanislavBreadless I have updated the other files as well. Let me know if there's more place I could update the same mistake.

**Comment by Deniallugo** [comment]
Hi @anthowen! Thanks for your help! Everything is fine!

**Comment by anthowen** [comment]
> Hi @anthowen! Thanks for your help! Everything is fine!

You're welcome! I'd love to contribute to zksync in-depth going forward!

**Pull request merged**
